[package]
name = "server"
version = "0.1.0"
authors = ["Stas Suturin <stanislav.suturin@gmail.com>"]
edition = "2020"

[dependencies]
clap = "2"

protector = { path = "./protector" }
thread_pool = { path = "./thread_pool" }
